-- Message Card Library taxonomy tags.
-- Run after content catalog migrations. Safe to re-run.

insert into content_tags (type, key, name, sort_order, is_active, created_at, updated_at)
values
  ('category', 'anxiety_worry', 'Anxiety & Worry', 10, true, now(), now()),
  ('category', 'peace_rest', 'Peace & Rest', 20, true, now(), now()),
  ('category', 'hope_waiting', 'Hope & Waiting', 30, true, now(), now()),
  ('category', 'strength_courage', 'Strength & Courage', 40, true, now(), now()),
  ('category', 'wisdom_guidance', 'Wisdom & Guidance', 50, true, now(), now()),
  ('category', 'loneliness_belonging', 'Loneliness & Belonging', 60, true, now(), now()),
  ('category', 'forgiveness_grace', 'Forgiveness & Grace', 70, true, now(), now()),
  ('category', 'gratitude_joy', 'Gratitude & Joy', 80, true, now(), now()),
  ('situation', 'future_uncertainty', 'When the future feels uncertain', 10, true, now(), now()),
  ('situation', 'relationships', 'When relationships feel heavy', 20, true, now(), now()),
  ('situation', 'decision_pressure', 'Before a big decision', 30, true, now(), now()),
  ('situation', 'money_work_pressure', 'When work or money weighs on you', 40, true, now(), now()),
  ('situation', 'health_fear', 'When health feels scary', 50, true, now(), now()),
  ('situation', 'feeling_behind', 'When you feel behind', 60, true, now(), now()),
  ('situation', 'spiritual_doubt', 'When faith feels distant', 70, true, now(), now()),
  ('situation', 'overwhelmed', 'When your mind feels crowded', 10, true, now(), now()),
  ('situation', 'before_sleep', 'Before sleep', 20, true, now(), now()),
  ('situation', 'busy_life', 'In a busy day', 30, true, now(), now()),
  ('situation', 'inner_noise', 'When thoughts will not stop', 40, true, now(), now()),
  ('situation', 'need_stillness', 'When you need stillness', 50, true, now(), now()),
  ('situation', 'waiting_season', 'In a waiting season', 10, true, now(), now()),
  ('situation', 'discouraged', 'When you feel discouraged', 20, true, now(), now()),
  ('situation', 'unanswered_prayer', 'When prayer feels unanswered', 30, true, now(), now()),
  ('situation', 'new_beginning', 'At a new beginning', 40, true, now(), now()),
  ('situation', 'long_process', 'When the process feels long', 50, true, now(), now()),
  ('situation', 'tired', 'When you are tired', 10, true, now(), now()),
  ('situation', 'afraid_to_start', 'When starting feels scary', 20, true, now(), now()),
  ('situation', 'facing_challenge', 'Facing a challenge', 30, true, now(), now()),
  ('situation', 'need_endurance', 'When you need endurance', 40, true, now(), now()),
  ('situation', 'standing_firm', 'When you want to stand firm', 50, true, now(), now()),
  ('situation', 'big_decision', 'Before a big decision', 10, true, now(), now()),
  ('situation', 'confused_direction', 'When direction is unclear', 20, true, now(), now()),
  ('situation', 'need_discernment', 'When you need discernment', 30, true, now(), now()),
  ('situation', 'work_school_choice', 'Choosing work or study', 40, true, now(), now()),
  ('situation', 'relationship_decision', 'In a relationship decision', 50, true, now(), now()),
  ('situation', 'feeling_alone', 'When you feel alone', 10, true, now(), now()),
  ('situation', 'left_out', 'When you feel left out', 20, true, now(), now()),
  ('situation', 'far_from_god', 'When God feels far away', 30, true, now(), now()),
  ('situation', 'need_comfort', 'When you need quiet comfort', 40, true, now(), now()),
  ('situation', 'missing_home', 'When you miss belonging', 50, true, now(), now()),
  ('situation', 'guilt', 'When guilt weighs on you', 10, true, now(), now()),
  ('situation', 'shame', 'When shame feels heavy', 20, true, now(), now()),
  ('situation', 'need_mercy', 'When you need mercy', 30, true, now(), now()),
  ('situation', 'starting_over', 'When you want to start again', 40, true, now(), now()),
  ('situation', 'forgiving_others', 'When forgiveness is hard', 50, true, now(), now()),
  ('situation', 'morning_gratitude', 'Morning gratitude', 10, true, now(), now()),
  ('situation', 'small_blessings', 'Small blessings', 20, true, now(), now()),
  ('situation', 'celebration', 'Celebration', 30, true, now(), now()),
  ('situation', 'contentment', 'Contentment', 40, true, now(), now()),
  ('situation', 'praise', 'Praise', 50, true, now(), now()),
  ('theme', 'trust', 'Trust', 10, true, now(), now()),
  ('theme', 'peace', 'Peace', 20, true, now(), now()),
  ('theme', 'hope', 'Hope', 30, true, now(), now()),
  ('theme', 'prayer', 'Prayer', 40, true, now(), now()),
  ('theme', 'waiting', 'Waiting', 50, true, now(), now()),
  ('theme', 'courage', 'Courage', 60, true, now(), now()),
  ('theme', 'wisdom', 'Wisdom', 70, true, now(), now()),
  ('theme', 'guidance', 'Guidance', 80, true, now(), now()),
  ('theme', 'grace', 'Grace', 90, true, now(), now()),
  ('theme', 'forgiveness', 'Forgiveness', 100, true, now(), now()),
  ('theme', 'comfort', 'Comfort', 110, true, now(), now()),
  ('theme', 'strength', 'Strength', 120, true, now(), now()),
  ('theme', 'joy', 'Joy', 130, true, now(), now()),
  ('theme', 'gratitude', 'Gratitude', 140, true, now(), now()),
  ('theme', 'identity', 'Identity', 150, true, now(), now()),
  ('theme', 'purpose', 'Purpose', 160, true, now(), now()),
  ('theme', 'faith', 'Faith', 170, true, now(), now()),
  ('theme', 'rest', 'Rest', 180, true, now(), now()),
  ('bible_context', 'psalms', 'Psalms', 10, true, now(), now()),
  ('bible_context', 'proverbs', 'Proverbs', 20, true, now(), now()),
  ('bible_context', 'gospels', 'Gospels', 30, true, now(), now()),
  ('bible_context', 'paul_letters', 'Paul''s Letters', 40, true, now(), now()),
  ('bible_context', 'prophets', 'Prophets', 50, true, now(), now()),
  ('bible_context', 'old_testament_story', 'Old Testament Story', 60, true, now(), now()),
  ('bible_context', 'jesus_words', 'Words of Jesus', 70, true, now(), now()),
  ('tone', 'comfort', 'Comfort', 10, true, now(), now()),
  ('tone', 'encouragement', 'Encouragement', 20, true, now(), now()),
  ('tone', 'reflection', 'Reflection', 30, true, now(), now()),
  ('tone', 'prayerful', 'Prayerful', 40, true, now(), now()),
  ('tone', 'gratitude', 'Gratitude', 50, true, now(), now()),
  ('tone', 'challenge', 'Challenge', 60, true, now(), now()),
  ('tone', 'assurance', 'Assurance', 70, true, now(), now()),
  ('share_intent', 'for_self', 'For yourself', 10, true, now(), now()),
  ('share_intent', 'send_comfort', 'Send comfort', 20, true, now(), now()),
  ('share_intent', 'send_encouragement', 'Send encouragement', 30, true, now(), now()),
  ('share_intent', 'morning_share', 'Morning share', 40, true, now(), now()),
  ('share_intent', 'night_share', 'Night share', 50, true, now(), now()),
  ('share_intent', 'thank_you', 'Say thank you', 60, true, now(), now()),
  ('share_intent', 'celebration', 'Share joy', 70, true, now(), now())
on conflict (type, key) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();
