-- Message Card Library taxonomy tags (v2 vocabulary).
-- Run after content catalog migrations. Safe to re-run.

-- Retire pre-v2 keys (kept in DB for history; hidden from pickers).
update content_tags
set is_active = false, updated_at = now()
where (type, key) in (
  ('category', 'anxiety_worry'),
  ('category', 'peace_rest'),
  ('category', 'loneliness_belonging'),
  ('category', 'forgiveness_grace'),
  ('category', 'gratitude_joy'),
  ('situation', 'relationships'),
  ('situation', 'decision_pressure'),
  ('situation', 'money_work_pressure'),
  ('situation', 'health_fear'),
  ('situation', 'feeling_behind'),
  ('situation', 'spiritual_doubt'),
  ('situation', 'overwhelmed'),
  ('situation', 'before_sleep'),
  ('situation', 'busy_life'),
  ('situation', 'inner_noise'),
  ('situation', 'need_stillness'),
  ('situation', 'discouraged'),
  ('situation', 'long_process'),
  ('situation', 'tired'),
  ('situation', 'afraid_to_start'),
  ('situation', 'need_endurance'),
  ('situation', 'standing_firm'),
  ('situation', 'big_decision'),
  ('situation', 'confused_direction'),
  ('situation', 'need_discernment'),
  ('situation', 'work_school_choice'),
  ('situation', 'relationship_decision'),
  ('situation', 'feeling_alone'),
  ('situation', 'left_out'),
  ('situation', 'need_comfort'),
  ('situation', 'missing_home'),
  ('situation', 'guilt'),
  ('situation', 'shame'),
  ('situation', 'need_mercy'),
  ('situation', 'starting_over'),
  ('situation', 'morning_gratitude'),
  ('situation', 'small_blessings'),
  ('situation', 'celebration'),
  ('situation', 'contentment'),
  ('situation', 'praise'),
  ('tone', 'comfort'),
  ('tone', 'encouragement'),
  ('tone', 'reflection'),
  ('tone', 'gratitude'),
  ('tone', 'challenge'),
  ('tone', 'assurance')
);

insert into content_tags (type, key, name, sort_order, is_active, created_at, updated_at)
values
  ('category', 'peace_anxiety', 'Peace & Anxiety', 10, true, now(), now()),
  ('category', 'hope_waiting', 'Hope & Waiting', 20, true, now(), now()),
  ('category', 'wisdom_guidance', 'Wisdom & Guidance', 30, true, now(), now()),
  ('category', 'strength_courage', 'Strength & Courage', 40, true, now(), now()),
  ('category', 'love_belonging', 'Love & Belonging', 50, true, now(), now()),
  ('category', 'grace_forgiveness', 'Grace & Forgiveness', 60, true, now(), now()),
  ('category', 'joy_gratitude', 'Joy & Gratitude', 70, true, now(), now()),
  ('category', 'identity_purpose', 'Identity & Purpose', 80, true, now(), now()),
  ('situation', 'future_uncertainty', 'When the future feels uncertain', 10, true, now(), now()),
  ('situation', 'major_decision', 'Before a big decision', 20, true, now(), now()),
  ('situation', 'feeling_overwhelmed', 'When you feel overwhelmed', 30, true, now(), now()),
  ('situation', 'waiting_season', 'In a waiting season', 40, true, now(), now()),
  ('situation', 'unanswered_prayer', 'When prayer feels unanswered', 50, true, now(), now()),
  ('situation', 'new_beginning', 'At a new beginning', 60, true, now(), now()),
  ('situation', 'feeling_tired', 'When you are tired', 70, true, now(), now()),
  ('situation', 'facing_challenge', 'Facing a challenge', 80, true, now(), now()),
  ('situation', 'feeling_lonely', 'When you feel alone', 90, true, now(), now()),
  ('situation', 'far_from_god', 'When God feels far away', 100, true, now(), now()),
  ('situation', 'guilt_shame', 'When guilt or shame feels heavy', 110, true, now(), now()),
  ('situation', 'forgiving_others', 'When forgiveness feels hard', 120, true, now(), now()),
  ('situation', 'morning_reset', 'At the start of the day', 130, true, now(), now()),
  ('situation', 'need_contentment', 'When you need contentment', 140, true, now(), now()),
  ('situation', 'life_transition', 'In a life transition', 150, true, now(), now()),
  ('theme', 'trust', 'Trust', 10, true, now(), now()),
  ('theme', 'peace', 'Peace', 20, true, now(), now()),
  ('theme', 'hope', 'Hope', 30, true, now(), now()),
  ('theme', 'prayer', 'Prayer', 40, true, now(), now()),
  ('theme', 'waiting', 'Waiting', 50, true, now(), now()),
  ('theme', 'courage', 'Courage', 60, true, now(), now()),
  ('theme', 'wisdom', 'Wisdom', 70, true, now(), now()),
  ('theme', 'guidance', 'Guidance', 80, true, now(), now()),
  ('theme', 'grace', 'Grace', 90, true, now(), now()),
  ('theme', 'forgiveness', 'Forgiveness', 100, true, now(), now()),
  ('theme', 'comfort', 'Comfort', 110, true, now(), now()),
  ('theme', 'strength', 'Strength', 120, true, now(), now()),
  ('theme', 'joy', 'Joy', 130, true, now(), now()),
  ('theme', 'gratitude', 'Gratitude', 140, true, now(), now()),
  ('theme', 'identity', 'Identity', 150, true, now(), now()),
  ('theme', 'purpose', 'Purpose', 160, true, now(), now()),
  ('theme', 'faith', 'Faith', 170, true, now(), now()),
  ('theme', 'rest', 'Rest', 180, true, now(), now()),
  ('theme', 'presence', 'Presence', 190, true, now(), now()),
  ('theme', 'love', 'Love', 200, true, now(), now()),
  ('bible_context', 'psalms', 'Psalms', 10, true, now(), now()),
  ('bible_context', 'proverbs', 'Proverbs', 20, true, now(), now()),
  ('bible_context', 'gospels', 'Gospels', 30, true, now(), now()),
  ('bible_context', 'paul_letters', 'Paul''s Letters', 40, true, now(), now()),
  ('bible_context', 'prophets', 'Prophets', 50, true, now(), now()),
  ('bible_context', 'old_testament_story', 'Old Testament Story', 60, true, now(), now()),
  ('bible_context', 'jesus_words', 'Words of Jesus', 70, true, now(), now()),
  ('tone', 'gentle', 'Gentle', 10, true, now(), now()),
  ('tone', 'comforting', 'Comforting', 20, true, now(), now()),
  ('tone', 'encouraging', 'Encouraging', 30, true, now(), now()),
  ('tone', 'reflective', 'Reflective', 40, true, now(), now()),
  ('tone', 'prayerful', 'Prayerful', 50, true, now(), now()),
  ('tone', 'assuring', 'Assuring', 60, true, now(), now()),
  ('tone', 'uplifting', 'Uplifting', 70, true, now(), now()),
  ('share_intent', 'for_self', 'For yourself', 10, true, now(), now()),
  ('share_intent', 'send_comfort', 'Send comfort', 20, true, now(), now()),
  ('share_intent', 'send_encouragement', 'Send encouragement', 30, true, now(), now()),
  ('share_intent', 'morning_share', 'Morning share', 40, true, now(), now()),
  ('share_intent', 'night_share', 'Night share', 50, true, now(), now()),
  ('share_intent', 'thank_you', 'Say thank you', 60, true, now(), now()),
  ('share_intent', 'celebration', 'Share joy', 70, true, now(), now())
on conflict (type, key) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();
