-- Reconcile plan_templates.estimated_minutes with bible_chapters.json (7s/verse avg).
-- Generated by: pnpm run plan-estimates:write-migration

begin;

update public.plan_templates
set estimated_minutes = 4,
    updated_at = now()
where template_key = 'bible_in_a_year'
  and coalesce(estimated_minutes, -1) <> 4;

update public.plan_templates
set estimated_minutes = 4,
    updated_at = now()
where template_key = 'the_story_of_joseph'
  and coalesce(estimated_minutes, -1) <> 4;

update public.plan_templates
set estimated_minutes = 6,
    updated_at = now()
where template_key = 'gospel_of_mark'
  and coalesce(estimated_minutes, -1) <> 6;

update public.plan_templates
set estimated_minutes = 2,
    updated_at = now()
where template_key = 'psalms_for_anxiety'
  and coalesce(estimated_minutes, -1) <> 2;

update public.plan_templates
set estimated_minutes = 4,
    updated_at = now()
where template_key = 'life_of_david'
  and coalesce(estimated_minutes, -1) <> 4;

update public.plan_templates
set estimated_minutes = 2,
    updated_at = now()
where template_key = 'jonah'
  and coalesce(estimated_minutes, -1) <> 2;

update public.plan_templates
set estimated_minutes = 6,
    updated_at = now()
where template_key = 'the_story_of_zacchaeus'
  and coalesce(estimated_minutes, -1) <> 6;

update public.plan_templates
set estimated_minutes = 4,
    updated_at = now()
where template_key = 'samuels_early_life'
  and coalesce(estimated_minutes, -1) <> 4;

commit;
